default: &default
  adapter: postgresql
  encoding: unicode

  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: Song_Texter_development

test:
  <<: *default
  database: Song_Texter_test

production:
  <<: *default
  database: Song_Texter_production
  username: Song_Texter
  password: <%= ENV['SONG_TEXTER_DATABASE_PASSWORD'] %>