default: &default
  adapter: postgresql
  encoding: unicode

  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: Song_Twitter_development

test:
  <<: *default
  database: Song_Twitter_test

production:
  <<: *default
  database: Song_Twitter_production
  username: Song_Twitter
  password: <%= ENV['SONG_TWITTER_DATABASE_PASSWORD'] %>